In [1]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

In [30]:
from fastai.imports import *
from fastai.structured import *

from pandas_summary import DataFrameSummary
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from IPython.display import display

from sklearn import metrics

from datetime import datetime, timedelta
import warnings
warnings.filterwarnings("ignore")

In [10]:
PATH = "Data/USACorona/"

In [12]:
!ls {PATH}

582631_1175383_compressed_UNCOVER_USAFacts_confirmed-covid-19-cases-in-us-by-state-and-county.csv.zip
582631_1175383_compressed_UNCOVER_USAFacts_confirmed-covid-19-deaths-in-us-by-state-and-county.csv.zip
cases.csv
deaths.csv

In [31]:
latest_date = datetime.today()- timedelta(days=2)
latest_date = latest_date.strftime('%m/%d/%y')[1:]

In [32]:
df_Death = pd.read_csv(f'{PATH}deaths.csv')[['countyFIPS', latest_date]]
df_Death = df_Death.rename(columns={'countyFIPS': 'county_fips',
                                                  latest_date: 'deaths'}).set_index('county_fips')
df_Cases = pd.read_csv(f'{PATH}cases.csv')[['countyFIPS', 'County Name', 'State', latest_date]]
df_Cases = df_Cases.rename(columns={'countyFIPS': 'county_fips',
                                                  latest_date: 'confirmed'}).set_index('county_fips')

KeyError: "None of [Index(['countyFIPS', '6/27/20'], dtype='object')] are in the [columns]"

In [20]:
def display_all(df):
    with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000): 
        display(df)

In [21]:
display_all(df_Death.tail().T)

,313105,313106,313107,313108,313109
county_fips,56045,56045,56045,56045,56045
county_name,Weston County,Weston County,Weston County,Weston County,Weston County
state_name,WY,WY,WY,WY,WY
state_fips,56,56,56,56,56
date,2020-04-24 00:00:00,2020-04-25 00:00:00,2020-04-26 00:00:00,2020-04-27 00:00:00,2020-04-28 00:00:00
deaths,0,0,0,0,0
lat,43.8396,43.8396,43.8396,43.8396,43.8396
long,-104.567,-104.567,-104.567,-104.567,-104.567
geometry,POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191)

In [22]:
display_all(df_Cases.tail().T)

,313105,313106,313107,313108,313109
county_fips,56045,56045,56045,56045,56045
county_name,Weston County,Weston County,Weston County,Weston County,Weston County
state_name,WY,WY,WY,WY,WY
state_fips,56,56,56,56,56
date,2020-04-24 00:00:00,2020-04-25 00:00:00,2020-04-26 00:00:00,2020-04-27 00:00:00,2020-04-28 00:00:00
confirmed,0,0,0,0,0
lat,43.8396,43.8396,43.8396,43.8396,43.8396
long,-104.567,-104.567,-104.567,-104.567,-104.567
geometry,POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191),POINT (-104.5674881 43.83961191)

In [23]:
display_all(df_Death.describe(include='all').T)

,count,unique,top,freq,first,last,mean,std,min,25%,50%,75%,max
county_fips,313110,NaN,NaN,NaN,NaT,NaT,29882.2,15522.1,0,18097,29123,45055,56045
county_name,313110,1882,Statewide Unallocated,4900,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_name,313110,51,TX,24990,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_fips,313110,NaN,NaN,NaN,NaT,NaT,30.2504,15.1576,1,18,29,45,56
date,313110,98,2020-02-23 00:00:00,3195,2020-01-22,2020-04-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deaths,313110,NaN,NaN,NaN,NaT,NaT,2.51845,47.9639,0,0,0,0,5281
lat,307916,NaN,NaN,NaN,NaT,NaT,38.4556,5.30712,19.6012,34.6932,38.3789,41.8094,69.3148
long,307916,NaN,NaN,NaN,NaT,NaT,-92.2684,12.8604,-164.035,-98.2385,-90.4002,-83.4368,-67.6281
geometry,307916,3142,POINT (-88.17657461 38.08706198),98,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
display_all(df_Cases.describe(include='all').T)

,count,unique,top,freq,first,last,mean,std,min,25%,50%,75%,max
county_fips,313110,NaN,NaN,NaN,NaT,NaT,29882.2,15522.1,0,18097,29123,45055,56045
county_name,313110,1882,Statewide Unallocated,4900,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_name,313110,51,TX,24990,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_fips,313110,NaN,NaN,NaN,NaT,NaT,30.2504,15.1576,1,18,29,45,56
date,313110,98,2020-02-23 00:00:00,3195,2020-01-22,2020-04-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
confirmed,313110,NaN,NaN,NaN,NaT,NaT,58.815,790.34,0,0,0,2,49929
lat,307916,NaN,NaN,NaN,NaT,NaT,38.4556,5.30712,19.6012,34.6932,38.3789,41.8094,69.3148
long,307916,NaN,NaN,NaN,NaT,NaT,-92.2684,12.8604,-164.035,-98.2385,-90.4002,-83.4368,-67.6281
geometry,307916,3142,POINT (-88.17657461 38.08706198),98,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df = df_Cases.join(df_Death)

ValueError: columns overlap but no suffix specified: Index(['county_fips', 'county_name', 'state_name', 'state_fips', 'date', 'lat',
       'long', 'geometry'],
      dtype='object')